import type { BunFile } from 'bun';
import type { ResponseOptions, ResponseWrapper, JsonValue, JsonObject, HttpStatus } from './types';
export declare class ResponseUtils implements ResponseWrapper {
    private headers;
    private _response;
    constructor();
    private defaultOptions;
    private mergeOptions;
    private handleError;
    private updateInternalResponse;
    private headersToObject;
    createResponse(body: BodyInit | null, options?: ResponseOptions): Response;
    json<T extends JsonValue>(data: T, options?: ResponseOptions): Response;
    text(text: string, options?: ResponseOptions): Response;
    html(html: string, options?: ResponseOptions): Response;
    redirect(url: string, options?: ResponseOptions): Response;
    notFound(message?: string, options?: ResponseOptions): Response;
    badRequest(message?: string, options?: ResponseOptions): Response;
    errorResponse(error: unknown): Response;
    serverError(message?: string | JsonObject, options?: ResponseOptions): Response;
    created<T extends object = Record<string, any>>(data: T, options?: ResponseOptions): Response;
    noContent(options?: ResponseOptions): Response;
    file(data: Blob | ArrayBuffer | ReadableStream | BunFile, filename: string, options?: ResponseOptions): Response;
    formData(data: FormData, options?: ResponseOptions): Response;
    stream(stream: ReadableStream<Uint8Array>, options?: ResponseOptions): Response;
    appendHeader(name: string, value: string): void;
    setHeader(name: string, value: string): void;
    setHeaders(headers: Record<string, string>): void;
    getHeader(name: string): string | null;
    getAllHeaders(): Record<string, string>;
    removeHeader(name: string): void;
    setResponse(response: Response): void;
    getResponse(): Response | null;
    getStatus(): HttpStatus;
    updateResponse(newResponse: Response): void;
}
