import type { BunFile } from 'bun';
import type { JSXElement, JSXChild, JSXResult, JSXComponent, JSXElementType, JSXProps, ResponseOptions, CookieOptions, ResponseWrapper, AsJsonValue, HttpStatus } from './types';
export declare class ResponseUtils implements ResponseWrapper {
    private headers;
    private _response;
    private transpiler;
    constructor();
    private defaultOptions;
    private mergeOptions;
    createResponse(body: BodyInit | null, options?: ResponseOptions): Response;
    private handleError;
    private updateInternalResponse;
    private serializeCookie;
    private headersToObject;
    renderJSX(element: JSXElement): JSXResult;
    createComponent<P extends JSXProps>(component: JSXComponent<P>): JSXComponent<P & {
        children?: JSXChild[];
    }>;
    jsx(type: JSXElementType, props: JSXProps | null, ...children: JSXChild[]): Response;
    json<T>(data: AsJsonValue<T>, options?: ResponseOptions): Response;
    text(text: string, options?: ResponseOptions): Response;
    html(html: string, options?: ResponseOptions): Response;
    redirect(url: string, options?: ResponseOptions): Response;
    notFound(message?: string, options?: ResponseOptions): Response;
    badRequest(message?: string, options?: ResponseOptions): Response;
    serverError(message?: string, options?: ResponseOptions): Response;
    created<T extends object = Record<string, any>>(data: T, options?: ResponseOptions): Response;
    noContent(options?: ResponseOptions): Response;
    file(data: Blob | ArrayBuffer | ReadableStream | BunFile, filename: string, options?: ResponseOptions): Response;
    formData(data: FormData, options?: ResponseOptions): Response;
    stream(stream: ReadableStream<Uint8Array>, options?: ResponseOptions): Response;
    setCookie(name: string, value: string, options?: CookieOptions): void;
    delCookie(name: string, options?: Omit<CookieOptions, 'maxAge' | 'sameSite'>): void;
    appendHeader(name: string, value: string): void;
    setHeader(name: string, value: string): void;
    setHeaders(headers: Record<string, string>): void;
    getHeader(name: string): string | null;
    getAllHeaders(): Record<string, string>;
    removeHeader(name: string): void;
    setResponse(response: Response): void;
    getResponse(): Response | null;
    getStatus(): HttpStatus;
    updateResponse(newResponse: Response): void;
}
